name: Only Tests

on:
  push:
    branches-ignore:
      - main
      - master

jobs:
  run-all-tests:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribuition: 'adopt'

      - name: Setup Maven
        uses: stCarolas/setup-maven@4.4
        with:
          maven-version: 3.8.2

      - name: All the Testes and Coverage Checks
        run: mvn clean install